apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    vol: prom-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany  # Modification du mode d'accès pour correspondre au PVC
  hostPath:
    path: /mnt/data/prometheus
