apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      vol: prom-storage  # Ajout du sélecteur pour correspondre au PV
