apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"env":"visuals"},"name":"grafana","namespace":"default"},"spec":{"selector":{"matchLabels":{"env":"visuals"}},"template":{"metadata":{"labels":{"env":"visuals"},"name":"grafana"},"spec":{"containers":[{"image":"grafana/grafana","name":"grafana","ports":[{"containerPort":3000}],"volumeMounts":[{"mountPath":"/var/lib/grafana/","name":"grafana-persistent-storage-store"},{"mountPath":"/etc/grafana/provisioning/datasources/datasource.yaml","name":"grafana-script","subPath":"datasource.yaml"}]}],"volumes":[{"name":"grafana-persistent-storage-store","persistentVolumeClaim":{"claimName":"grafana-storage-pvc"}},{"configMap":{"name":"grafana-config"},"name":"grafana-script"}]}}}}
  creationTimestamp: "2024-06-19T15:30:45Z"
  generation: 1
  labels:
    env: visuals
  name: grafana
  namespace: default
  resourceVersion: "15419"
  uid: 44eb6a3f-9686-439d-8720-d3ac8b38d6fd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      env: visuals
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        env: visuals
      name: grafana
    spec:
      containers:
      - image: grafana/grafana
        imagePullPolicy: Always
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/grafana/
          name: grafana-persistent-storage-store
        - mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
          name: grafana-script
          subPath: datasource.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: grafana-persistent-storage-store
        persistentVolumeClaim:
          claimName: grafana-storage-pvc
      - configMap:
          defaultMode: 420
          name: grafana-config
        name: grafana-script
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-06-19T15:30:46Z"
    lastUpdateTime: "2024-06-19T15:37:50Z"
    message: ReplicaSet "grafana-68fb94488c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-06-19T16:10:32Z"
    lastUpdateTime: "2024-06-19T16:10:32Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
